/* tone is determined by the writing style and the overall mood of the book
using language to determine this, so there will actually be several tones that a book could have
and the profile of a book tone-wise will be determined by the language dictionary here
so a book will have a vector for tone that takes into account the different tones by language to draw a complete profile */

export const TONES_DICTIONARY = {
  "absurd": ["bizarre", "ridiculous", "ludicrous", "surreal", "nonsense", "nonsensical", "preposterous", "weird"],
  "acerbic": ["sharp", "sarcastic", "biting", "stinging", "scathing", "sour", "acidic", "harsh", "cutting"],
  "ambivalent": ["unsure", "conflicted", "undecided", "mixed", "torn", "uncertain", "wavering", "hesitant"],
  "amusing": ["funny", "entertaining", "witty", "humorous", "charming", "delightful", "lighthearted", "diverting"],
  "animated": ["lively", "vibrant", "energetic", "spirited", "dynamic", "passionate", "vivid", "expressive"],
  "ardent": ["passionate", "fervent", "intense", "zealous", "eager", "devoted", "fierce", "burning"],
  "assertive": ["confident", "bold", "firm", "strong", "decisive", "authoritative", "commanding", "insistent"],
  "awestruck": ["amazed", "astonished", "wonder", "marveled", "breathless", "stunned", "overwhelmed", "magnificent"],
  "candid": ["honest", "open", "truthful", "sincere", "frank", "blunt", "unfiltered", "straightforward"],
  "celebratory": ["festive", "triumphant", "joyous", "exultant", "cheering", "honoring", "praising", "glorious"],
  "charming": ["delightful", "enchanting", "lovely", "appealing", "captivating", "alluring", "winning", "sweet"],
  "chatty": ["talkative", "conversational", "casual", "informal", "gossipy", "friendly", "approachable"],
  "cheerful": ["happy", "bright", "sunny", "joyful", "glad", "merry", "buoyant", "lighthearted"],
  "colloquial": ["slang", "informal", "everyday", "vernacular", "conversational", "casual", "idiomatic"],
  "comical": ["hilarious", "funny", "laughable", "humorous", "silly", "amusing", "slapstick", "jesting"],
  "compassionate": ["kind", "sympathetic", "empathetic", "caring", "merciful", "tender", "warm", "understanding"],
  "complex": ["intricate", "complicated", "deep", "layered", "nuanced", "multifaceted", "dense", "perplexing"],
  "curious": ["inquisitive", "searching", "questioning", "puzzled", "interested", "exploring", "intrigued"],
  "cynical": ["skeptical", "distrustful", "mocking", "scornful", "pessimistic", "sardonic", "jaded", "bleak"],
  "dark": ["grim", "bleak", "morbid", "somber", "sinister", "macabre", "twisted", "gloomy", "shadowy"],
  "defiant": ["rebellious", "resistant", "bold", "stubborn", "unyielding", "disobedient", "challenging"],
  "deliberate": ["intentional", "careful", "measured", "calculated", "conscious", "slow", "methodical"],
  "desperate": ["hopeless", "frantic", "anguished", "reckless", "dire", "panicked", "wild", "fearing"],
  "derisive": ["mocking", "scornful", "ridiculing", "scathing", "contemptuous", "jeering", "disdainful"],
  "dignified": ["noble", "stately", "honorable", "solemn", "graceful", "poised", "respectable", "majestic"],
  "diplomatic": ["tactful", "polite", "careful", "strategic", "neutral", "mediated", "respectful"],
  "direct": ["straightforward", "blunt", "plain", "explicit", "clear", "unvarnished", "matter-of-fact"],
  "disarming": ["charming", "endearing", "winning", "sweet", "softening", "likable", "persuasive"],
  "discerning": ["perceptive", "sharp", "insightful", "wise", "shrewd", "clever", "analytical", "critical"],
  "disillusioned": ["disappointed", "letdown", "bitter", "jaded", "cynical", "discouraged", "unenchanted"],
  "earnest": ["serious", "sincere", "grave", "solemn", "heartfelt", "honest", "dedicated", "intense"],
  "encouraging": ["hopeful", "inspiring", "supportive", "uplifting", "reassuring", "positive", "promising"],
  "enthusiastic": ["excited", "eager", "passionate", "thrilled", "energetic", "animated", "zealous"],
  "epic": ["grand", "heroic", "monumental", "vast", "sweeping", "legendary", "historic", "massive"],
  "erudite": ["learned", "scholarly", "intellectual", "wise", "educated", "academic", "profound"],
  "evocative": ["expressive", "vivid", "moving", "suggestive", "poetic", "haunting", "resonant"],
  "exuberant": ["joyful", "vibrant", "overflowing", "enthusiastic", "excited", "energetic", "high-spirited"],
  "facetious": ["playful", "flippant", "tongue-in-cheek", "ironic", "joking", "teasing", "lighthearted"],
  "farcical": ["absurd", "mocking", "ridiculous", "slapstick", "satirical", "ludicrous", "caricature"],
  "flippant": ["disrespectful", "shallow", "glib", "carefree", "casual", "thoughtless", "frivolous"],
  "forceful": ["powerful", "strong", "aggressive", "assertive", "compelling", "vigorous", "intense"],
  "formal": ["official", "stately", "serious", "rigid", "academic", "proper", "structured", "polite"],
  "forthright": ["honest", "direct", "frank", "blunt", "outspoken", "candid", "straightforward"],
  "frank": ["honest", "direct", "open", "plain", "blunt", "truthful", "unconcealed"],
  "gentle": ["soft", "mild", "kind", "tender", "calm", "peaceful", "quiet", "soothing"],
  "ghoulish": ["macabre", "morbid", "horrific", "grim", "monstrous", "scary", "sinister", "frightening"],
  "gullible": ["naive", "trusting", "innocent", "fooled", "susceptible", "unwary", "green"],
  "humble": ["modest", "meek", "unpretentious", "simple", "respectful", "lowly", "submissive"],
  "humorous": ["funny", "witty", "amusing", "comic", "hilarious", "jocular", "playful"],
  "inane": ["silly", "foolish", "stupid", "pointless", "mindless", "frivolous", "empty", "vacuous"],
  "intense": ["fierce", "powerful", "heavy", "deep", "sharp", "passionate", "extreme", "overwhelming"],
  "intimate": ["personal", "private", "close", "secret", "cozy", "deep", "heartfelt", "tender"],
  "ironic": ["sarcastic", "unexpected", "paradoxical", "satirical", "mocking", "cynical", "wry"],
  "irreverent": ["disrespectful", "cheeky", "impudent", "bold", "flippant", "rebellious", "mocking"],
  "jaded": ["bored", "tired", "weary", "dulled", "cynical", "unmoved", "sated", "exhausted"],
  "joyful": ["happy", "glad", "delighted", "exuberant", "blissful", "radiant", "rejoicing"],
  "light-hearted": ["carefree", "cheerful", "happy", "easygoing", "playful", "sunny", "untroubled"],
  "nostalgic": ["wistful", "longing", "sentimental", "homesick", "reminiscent", "past", "memories"],
  "objective": ["neutral", "fair", "impartial", "unbiased", "detached", "factual", "logical"],
  "optimistic": ["hopeful", "positive", "bright", "promising", "confident", "cheerful", "encouraging"],
  "pensive": ["thoughtful", "reflective", "dreamy", "wistful", "serious", "quiet", "meditative"],
  "persuasive": ["convincing", "compelling", "influential", "winning", "strong", "effective", "plausible"],
  "pessimistic": ["gloomy", "negative", "bleak", "dark", "defeatist", "cynical", "hopeless"],
  "philosophical": ["thoughtful", "wise", "deep", "reflective", "analytical", "rational", "logical"],
  "playful": ["fun", "frisky", "mischievous", "cheerful", "lively", "sportive", "lighthearted"],
  "pragmatic": ["practical", "realistic", "sensible", "logical", "matter-of-fact", "efficient", "functional"],
  "satirical": ["mocking", "ironic", "sarcastic", "parody", "lampoon", "wry", "critical"],
  "sarcastic": ["ironic", "sharp", "biting", "acerbic", "mocking", "cutting", "taunting"],
  "sentimental": ["emotional", "mushy", "tender", "romantic", "nostalgic", "touching", "heartfelt"],
  "sincere": ["honest", "heartfelt", "genuine", "true", "earnest", "frank", "real"],
  "solemn": ["serious", "grave", "formal", "somber", "dignified", "earnest", "sober"],
  "sympathetic": ["caring", "kind", "warm", "compassionate", "supportive", "pitying", "understanding"],
  "thoughtful": ["considerate", "reflective", "pensive", "kind", "careful", "deep", "attentive"],
  "tolerant": ["patient", "open-minded", "accepting", "lenient", "understanding", "fair", "broad-minded"],
  "unassuming": ["modest", "humble", "quiet", "simple", "plain", "meek", "unobtrusive"],
  "whimsical": ["playful", "fanciful", "quaint", "mischievous", "magical", "eccentric", "curious"],
  "witty": ["clever", "sharp", "smart", "funny", "bright", "amusing", "quick-witted"],
  "world-weary": ["tired", "jaded", "exhausted", "bored", "cynical", "spent", "worn"]
};
